export interface ArticleSection {
  heading: string;
  paragraphs: string[];
}

// Editorial copy for the shared fixtures, whose domain DTO currently has no body.
export const ARTICLE_CONTENT: Record<string, ArticleSection[]> = {
  'getting-started-with-productivity-apps': [
    { heading: 'Start with one workflow', paragraphs: ['Before choosing an app, write down a recurring task that takes more effort than it should. Collecting meeting actions, planning a week, or tracking a shared deadline are useful starting points. Define what a better result would look like so that you can evaluate the tool against your own needs.', 'Move one small project into your chosen task manager. Give each task an owner and a clear next action. Keep reference material separate from commitments, and avoid migrating your entire archive before you know the workflow works.'] },
    { heading: 'Make the routine sustainable', paragraphs: ['Set aside a short review at the end of each week. Close completed tasks, revisit overdue items, and remove work that no longer matters. A simple list that you trust is more useful than an elaborate dashboard that nobody maintains.', 'Review notification settings with your team and keep only alerts that require action. After a trial period, compare missed deadlines and time spent organizing work with your starting point. Keep the features that help and simplify the rest.'] },
  ],
  'tech-trends-2024': [
    { heading: 'Evaluate a trend through a concrete problem', paragraphs: ['AI assistants, edge computing, and new development frameworks offer different ways to build software. Their usefulness depends on the workload. Begin with a bottleneck you can measure, such as slow responses, repetitive support requests, or difficult deployment procedures.', 'For an AI feature, assemble representative examples and define what an acceptable answer looks like. Include ambiguous requests and failure cases. Preserve a way for a person to review or correct the result before expanding the experiment.'] },
    { heading: 'Account for the cost of operating it', paragraphs: ['Moving computation closer to users may reduce network delay, but it also changes where data lives and how releases are coordinated. Compare a small prototype with your current system under similar conditions.', 'Adopt a technology only after considering monitoring, maintenance, team experience, and an exit path. Record the reason for your choice so that the decision can be revisited when requirements change.'] },
  ],
  'design-principles-modern-apps': [
    { heading: 'Make the next action clear', paragraphs: ['Start each screen with the task a person came to complete. Use a descriptive heading, group related information, and reserve the strongest visual emphasis for the primary action. Familiar words help people decide without learning your internal terminology.', 'A form should explain the expected input before an error occurs. Give every control a visible label and place useful validation next to the affected field. Preserve entered values when something goes wrong.'] },
    { heading: 'Design every state', paragraphs: ['An empty collection should explain how to add the first item. A missing record should offer a route back to useful content. Loading and error states deserve the same attention as a populated screen.', 'Check the interface with a keyboard, a narrow viewport, and enlarged text. Visible focus, readable contrast, and a logical heading order make the product easier to use across different devices and abilities.'] },
  ],
  'building-scalable-applications-with-modern-architecture': [
    { heading: 'Measure before distributing', paragraphs: ['Start with a realistic workload and measure request latency, throughput, and resource use. Identify whether time is spent waiting on a database, an external service, or computation. Scaling the wrong layer adds cost without removing the bottleneck.', 'Keep application instances stateless where practical. Store shared state deliberately, and make background work safe to retry so that an interrupted worker does not duplicate an operation.'] },
    { heading: 'Plan for overload', paragraphs: ['Bound queues, limit expensive requests, and define timeouts between services. Cache data only when its freshness requirements are clear. Observe saturation as well as errors so that capacity problems appear before a complete outage.', 'Exercise failure scenarios with a small rollout. A system is easier to scale when its team can explain how it behaves under pressure and reverse a change quickly.'] },
  ],
  'the-future-of-web-development-trends-to-watch': [
    { heading: 'Choose capabilities that serve users', paragraphs: ['New frameworks and browser capabilities should be evaluated against a user task. Build a small end-to-end example and measure loading time, interaction latency, and accessibility on the devices your audience uses.', 'For AI-assisted experiences, make uncertainty visible and provide a way to recover from incorrect output. For edge delivery, check which data can be cached and which requests need a consistent source of truth.'] },
    { heading: 'Keep a stable foundation', paragraphs: ['Progressive enhancement, semantic HTML, and clear API boundaries reduce the cost of changing tools. Document why a dependency is needed and how the application would behave if it became unavailable.', 'Treat experiments as bounded projects with a success criterion. A trend becomes useful when it produces a measurable improvement that the team can maintain.'] },
  ],
  'security-best-practices-for-modern-applications': [
    { heading: 'Define trust boundaries', paragraphs: ['Identify where untrusted input enters the application and where permissions are checked. Validate input at service boundaries, use parameterized database queries, and enforce authorization for each protected operation on the server.', 'Give services only the access they need. Keep secrets out of source files and logs, and separate credentials across environments so that a development mistake does not grant production access.'] },
    { heading: 'Make recovery part of the design', paragraphs: ['Track dependency updates and establish a process for reviewing vulnerabilities. Log security-relevant events without collecting unnecessary personal data or credentials.', 'Test backups and account recovery procedures. A documented response plan should identify who can revoke access, rotate credentials, and communicate an incident when something goes wrong.'] },
  ],
  'microservices-vs-monoliths-choosing-the-right-architecture': [
    { heading: 'Start with team and domain boundaries', paragraphs: ['A modular monolith keeps deployment and local development simple while allowing clear boundaries between business capabilities. It is a useful starting point when one team owns most changes and the domain is still evolving.', 'Independent services can help teams release separately or scale a specific workload. They also introduce network failures, distributed tracing, and coordination across data stores. These costs should solve a concrete organizational or operational problem.'] },
    { heading: 'Extract a boundary deliberately', paragraphs: ['Choose a capability with a clear owner and a small, stable interface. Define how changes propagate and what happens when the dependency is unavailable. Avoid sharing database tables between independently deployed services.', 'Compare the new service with the simpler design using release frequency, reliability, and maintenance effort. Architectural boundaries can evolve as the product and team grow.'] },
  ],
  'devops-best-practices-for-continuous-deployment': [
    { heading: 'Build a repeatable path to production', paragraphs: ['Create one versioned build artifact and promote it through environments. Automate checks for the behavior that matters to users and keep configuration separate from the artifact.', 'Use short-lived changes and make deployment steps reproducible. A pipeline should stop with a clear explanation when a required check fails, rather than leaving operators to guess which steps completed.'] },
    { heading: 'Release with feedback', paragraphs: ['Roll out changes gradually and watch user-facing errors and latency. Define the conditions for pausing a release before starting it. Database changes need to remain compatible with the application versions that may run during a rollout.', 'Practice rollback or a forward repair on a safe environment. Use incidents to improve the pipeline and documentation so that the next release is easier to understand and recover.'] },
  ],
};
