export const APP_CONFIG = Symbol('APP_CONFIG');
export const IDENTITY_AUTH_SERVICE = Symbol('IDENTITY_AUTH_SERVICE');
export const OAUTH_CODE_EXCHANGER = Symbol('OAUTH_CODE_EXCHANGER');
export const SWAGGER_DOCUMENT = Symbol('SWAGGER_DOCUMENT');

export const GOOGLE_CODE_EXCHANGER = Symbol('GOOGLE_CODE_EXCHANGER');
export const GITHUB_CODE_EXCHANGER = Symbol('GITHUB_CODE_EXCHANGER');
export const USER_PROVISIONER = Symbol('USER_PROVISIONER');
export const TOKEN_GENERATOR = Symbol('TOKEN_GENERATOR');
export const REST_SESSION_GATEWAY = Symbol('REST_SESSION_GATEWAY');

export const GOOGLE_AUTHENTICATION_STRATEGY_FACTORY = Symbol('GOOGLE_AUTHENTICATION_STRATEGY_FACTORY');
export const GITHUB_AUTHENTICATION_STRATEGY_FACTORY = Symbol('GITHUB_AUTHENTICATION_STRATEGY_FACTORY');
export const EMAIL_AUTHENTICATION_STRATEGY_FACTORY = Symbol('EMAIL_AUTHENTICATION_STRATEGY_FACTORY');
export const ANONYMOUS_AUTHENTICATION_STRATEGY_FACTORY = Symbol('ANONYMOUS_AUTHENTICATION_STRATEGY_FACTORY');