trigger:
  branches:
    include:
      - main

variables:
  IMAGE_NAME: store-app-scrapper
  IMAGE_TAG: latest

pool:
  name: 'Local Server Pool'

steps:
  - script: |
      kubectl apply -f apps/scrappers/store-app/provisioning/k8s/namespace.yaml
    displayName: 'Apply namespace'

  - script: |
      kubectl apply -f apps/scrappers/store-app/provisioning/k8s/service-account.yaml
    displayName: 'Apply service account'

  - script: |
      kubectl apply -f apps/scrappers/store-app/provisioning/k8s/scrapper.configmap.yaml
    displayName: 'Apply ConfigMap for RabbitMQ discovery'
