apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firebase-auth-validator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: wapps-platform
  source:
    repoURL: https://github.com/Gitarzysta92/wapps.git
    targetRevision: HEAD
    path: environments/dev/apps/firebase-auth-validator-kustomization
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Ignore differences in kustomization image tags to allow CI/CD to update them
  ignoreDifferences:
    - group: kustomize.config.k8s.io
      kind: Kustomization
      jqPathExpressions:
        - '.images[]?.newTag'

