apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: wapps-platform
  source:
    # TODO: Move repoURL to environment variable or Kustomize parameter
    # Currently hardcoded to: https://github.com/Gitarzysta92/wapps.git
    repoURL: https://github.com/Gitarzysta92/wapps.git
    targetRevision: HEAD
    path: platform/cluster/kong
    # Using directory mode for raw Kubernetes manifests
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
