apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    description: "MinIO object storage (GitOps-managed Helm deployment)"
spec:
  project: wapps-platform
  sources:
    - repoURL: https://charts.min.io/
      chart: minio
      targetRevision: 5.*.*  # Use latest 5.x available
      helm:
        releaseName: minio
        valueFiles:
          - $values/platform/cluster/minio/values.yaml
        parameters:
          - name: rootUser
            value: "admin"
          - name: rootPassword
            value: "changeme"
    - repoURL: https://github.com/Gitarzysta92/wapps.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
