apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    description: "RabbitMQ message broker (GitOps-managed Helm deployment)"
spec:
  project: wapps-platform
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: rabbitmq
      targetRevision: 16.0.14  # Latest available version in Bitnami repo
      helm:
        releaseName: rabbitmq
        valueFiles:
          - $values/platform/cluster/rabbitmq/values.yaml
        parameters:
          - name: auth.username
            value: "admin"
          - name: auth.password
            value: "changeme"
          - name: auth.erlangCookie
            value: "secretcookie"
          - name: auth.updatePasswordOnStartup
            value: "true"
    - repoURL: https://github.com/Gitarzysta92/wapps.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
