name: 'Test and Lint'
description: 'Run tests and linting for the application'
inputs:
  app-name:
    description: 'Nx application name'
    required: true
  working-directory:
    description: 'Working directory for the command'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        echo "Installing dependencies for ${{ inputs.app-name }}..."
        npm ci || { echo "❌ npm ci failed"; exit 1; }
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run linting
      run: |
        echo "Running linting for ${{ inputs.app-name }}..."
        npx nx lint ${{ inputs.app-name }} || { echo "❌ Linting failed for ${{ inputs.app-name }}"; exit 1; }
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run tests
      run: |
        echo "Running tests for ${{ inputs.app-name }}..."
        npx nx test ${{ inputs.app-name }} --coverage --ci || { echo "❌ Tests failed for ${{ inputs.app-name }}"; exit 1; }
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Upload coverage reports
      if: always()
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: ${{ inputs.app-name }}
        name: ${{ inputs.app-name }}-coverage
        fail_ci_if_error: false
