apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy grants admin role to all users
  # TODO: Replace with dedicated CI/CD service account with limited permissions
  policy.default: role:admin
