---
- name: Host Environment Provisioning - Main Playbook
  hosts: localhost
  become: yes
  vars:
    target_env: "{{ target_env | default('staging') }}"
    git_sha: "{{ git_sha | default('main') }}"
    apps_dir: "/opt/wapps"
    ansible_user: "{{ ansible_env.USER | default('root') }}"

  tasks:
    - name: Display provisioning start
      debug:
        msg: |
          Starting host environment provisioning...
          Environment: {{ target_env }}
          Git SHA: {{ git_sha }}
          Target directory: {{ apps_dir }}

    - name: Include system configuration
      include_tasks: system/configure.yml
      when: target_env in ['development', 'staging', 'production']

    - name: Include K3s installation
      include_tasks: k3s/install.yml
      when: target_env in ['development', 'staging', 'production']

    - name: Include ArgoCD installation
      include_tasks: argocd/install.yml
      when: target_env in ['development', 'staging', 'production']

    - name: Include Node Exporter installation
      include_tasks: node-exporter/install.yml
      when: target_env in ['development', 'staging', 'production']

    - name: Include Tailscale installation
      include_tasks: tailscale/install.yml
      when: target_env in ['development', 'staging', 'production']

    - name: Include Ingress installation
      include_tasks: ingress/install.yml
      when: target_env in ['development', 'staging', 'production']

    - name: Include Tailscale DNS configuration
      include_tasks: tailscale/dns.yml
      when: target_env in ['development', 'staging', 'production']

    - name: Display provisioning summary
      debug:
        msg: |
          Host provisioning completed successfully!
          Environment: {{ target_env }}
          Git SHA: {{ git_sha }}
          Applications directory: {{ apps_dir }}
          Installed services:
            - ArgoCD (port 30080) - GitOps CD
            - GitHub Actions Runner - CI/CD
            - K3s (port 6443) - Kubernetes
            - Node Exporter (port 9100) - Metrics
            - Tailscale (port 41641) - VPN networking
            - NTP - Time synchronization
          Logs directory: {{ apps_dir }}/logs
