apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-bff
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: catalog-bff
    app.kubernetes.io/component: bff
    app.kubernetes.io/part-of: catalog
spec:
  project: wapps-platform
  source:
    repoURL: https://github.com/Gitarzysta92/wapps.git
    targetRevision: HEAD
    path: environments/dev/apps/catalog-bff-kustomization
  destination:
    server: https://kubernetes.default.svc
    namespace: catalog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

