apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: editor-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: editor-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: editorial
spec:
  project: wapps-platform
  source:
    repoURL: https://github.com/Gitarzysta92/wapps.git
    targetRevision: HEAD
    path: environments/dev/apps/editor-agent-kustomization
  destination:
    server: https://kubernetes.default.svc
    namespace: editorial
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

