name: 'Deploy to ArgoCD'
description: 'Deploy application to ArgoCD'
inputs:
  app-name:
    description: 'ArgoCD application name'
    required: true
  image-name:
    description: 'Docker image name (defaults to app-name if not provided)'
    required: false
  namespace:
    description: 'ArgoCD namespace'
    required: true
    default: 'argocd'
  argocd-server:
    description: 'ArgoCD server URL'
    required: true
  argocd-username:
    description: 'ArgoCD username (for user/password authentication)'
    required: false
  argocd-password:
    description: 'ArgoCD password (for user/password authentication)'
    required: false
  argocd-token:
    description: 'ArgoCD authentication token (alternative to username/password)'
    required: false
  image-tag:
    description: 'Docker image tag to deploy'
    required: true
  environment:
    description: 'Target environment (dev/prod)'
    required: true
    default: 'dev'

runs:
  using: 'composite'
  steps:
    - name: Install ArgoCD CLI
      run: |
        if ! command -v argocd &> /dev/null; then
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          mkdir -p $HOME/.local/bin
          mv argocd-linux-amd64 $HOME/.local/bin/argocd
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        fi
      shell: bash

    - name: Login to ArgoCD
      run: |
        login_with_token() {
          echo "Logging in with token authentication"
          argocd login ${{ inputs.argocd-server }} --auth-token "${{ inputs.argocd-token }}" --insecure --grpc-web
        }

        login_with_userpass() {
          echo "Logging in with username/password authentication"
          argocd login ${{ inputs.argocd-server }} --username ${{ inputs.argocd-username }} --password ${{ inputs.argocd-password }} --insecure --grpc-web
        }

        if [ -n "${{ inputs.argocd-token }}" ]; then
          if ! login_with_token; then
            echo "Token login failed; falling back to username/password (if provided)."
            if [ -n "${{ inputs.argocd-username }}" ] && [ -n "${{ inputs.argocd-password }}" ]; then
              login_with_userpass
            else
              exit 1
            fi
          fi
        elif [ -n "${{ inputs.argocd-username }}" ] && [ -n "${{ inputs.argocd-password }}" ]; then
          login_with_userpass
        else
          echo "Error: Either argocd-token or both argocd-username and argocd-password must be provided"
          exit 1
        fi
      shell: bash

    - name: Set kustomize image override
      run: |
        IMAGE_NAME="${{ inputs.image-name }}"
        if [ -z "$IMAGE_NAME" ]; then
          IMAGE_NAME="${{ inputs.app-name }}"
        fi
        
        echo "Setting kustomize image for ${{ inputs.app-name }}: ${IMAGE_NAME}=${{ inputs.image-tag }}"
        argocd app set ${{ inputs.app-name }} \
          --kustomize-image "${IMAGE_NAME}=${{ inputs.image-tag }}" \
          --grpc-web
      shell: bash

    # Manual sync is disabled because ArgoCD applications have auto-sync enabled.
    # The 'argocd app set' command above triggers an automatic sync operation.
    # Running 'argocd app sync' here causes a race condition error:
    # "rpc error: code = FailedPrecondition desc = another operation is already in progress"
    # because the auto-sync from the image override is still running.
    #
    # - name: Sync ArgoCD application
    #   run: |
    #     argocd app sync ${{ inputs.app-name }} --grpc-web
    #   shell: bash

    - name: Wait for auto-sync deployment to be ready
      run: |
        echo "Waiting for ArgoCD auto-sync to complete..."
        sleep 5  # Give ArgoCD a moment to detect the change and start auto-syncing
        argocd app wait ${{ inputs.app-name }} --timeout 1000 --grpc-web
        echo "✅ Deployment completed successfully"
      shell: bash
