name: 'Deploy to ArgoCD'
description: 'Deploy application to ArgoCD'
inputs:
  app-name:
    description: 'ArgoCD application name'
    required: true
  namespace:
    description: 'ArgoCD namespace'
    required: true
    default: 'argocd'
  argocd-server:
    description: 'ArgoCD server URL'
    required: true
  argocd-username:
    description: 'ArgoCD username'
    required: true
  argocd-password:
    description: 'ArgoCD password'
    required: true
  image-tag:
    description: 'Docker image tag to deploy'
    required: true
  environment:
    description: 'Target environment (dev/prod)'
    required: true
    default: 'dev'

runs:
  using: 'composite'
  steps:
    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
        rm argocd-linux-amd64
      shell: bash

    - name: Login to ArgoCD
      run: |
        argocd login ${{ inputs.argocd-server }} --username ${{ inputs.argocd-username }} --password ${{ inputs.argocd-password }} --insecure
      shell: bash

    - name: Set image tag in ArgoCD application
      run: |
        argocd app set ${{ inputs.app-name }} \
          --namespace ${{ inputs.namespace }} \
          --parameter image.tag=${{ inputs.image-tag }}
      shell: bash

    - name: Sync ArgoCD application
      run: |
        argocd app sync ${{ inputs.app-name }} --namespace ${{ inputs.namespace }} --force
      shell: bash

    - name: Wait for deployment to be ready
      run: |
        argocd app wait ${{ inputs.app-name }} --namespace ${{ inputs.namespace }} --timeout 300
      shell: bash
