apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: wapps-platform
  source:
    repoURL: https://github.com/your-org/wapps.git
    targetRevision: HEAD
    path: argocd/applications/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: editorial
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
