---
- name: Create ArgoCD namespace
  shell: kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
  register: argocd_namespace
  changed_when: argocd_namespace.rc != 0
  failed_when: false

- name: Install ArgoCD via kubectl
  shell: |
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  register: argocd_install

- name: Wait for ArgoCD to be ready
  shell: kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n argocd
  register: argocd_wait
  changed_when: false

- name: Install ArgoCD CLI
  get_url:
    url: "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64"
    dest: /usr/local/bin/argocd
    mode: '0755'

- name: Patch ArgoCD server service to NodePort with HTTPS
  shell: |
    kubectl patch svc argocd-server -n argocd -p '{"spec":{"type":"NodePort","ports":[{"port":443,"nodePort":32443,"targetPort":8080}]}}'
  register: argocd_patch

- name: Set ArgoCD admin password
  shell: |
    kubectl create secret generic argocd-initial-admin-secret \
      --from-literal=password="{{ argocd_admin_password }}" \
      -n argocd \
      --dry-run=client -o yaml | kubectl apply -f -
  when: argocd_admin_password is defined
  register: argocd_password_set

- name: Get ArgoCD admin password (fallback to auto-generated)
  shell: |
    kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  register: argocd_password
  changed_when: false
  when: argocd_admin_password is not defined

- name: Display ArgoCD access information
  debug:
    msg: |
      ArgoCD installed successfully!
      Access URL: https://argocd.\{\{ tailscale_domain | default('development-wapps.ts.net') }}
      Username: admin
      Password: {{ argocd_admin_password if argocd_admin_password is defined else argocd_password.stdout }}
      
      Alternative access (direct IP):
      - HTTPS: https://{{ ansible_default_ipv4.address }}:32443
      - HTTP: http://{{ ansible_default_ipv4.address }}:32080
