location = /_validate {
    internal;
    proxy_pass http://local_auth$validation_path;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header Authorization $http_authorization;
}
location /api/discussions {
    include /etc/nginx/local/auth.conf;
    proxy_pass http://discussion:1338;
}
location ~ ^/api/(me|registration|password-recovery|admin/users)(/|$) {
    include /etc/nginx/local/auth.conf;
    proxy_pass http://account-management:1340;
}
location /api/ {
    include /etc/nginx/local/auth.conf;
    proxy_pass http://catalog-bff:3000;
}
location /auth/ { proxy_pass http://firebase-auth-validator:8080; }
location = /health { return 200 "healthy\n"; }
