trigger:
  branches:
    include:
      - master
  paths:
    include:
      - apps/services/editorial/**

variables:
  IMAGE_NAME: editorial
  IMAGE_TAG: $(Build.BuildId)

pool:
  name: 'Local Server Pool'

steps:
  # 1. Setup Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Use Node.js 18'

  # 2. Install dependencies
  - script: |
      npm ci
    displayName: 'Install dependencies'

  # 3. Generate minimal package.json for Strapi compatibility
  - script: |
      echo '{ "name": "editorial", "private": true, "version": "0.0.0" }' > apps/services/editorial/package.json
    displayName: 'Create minimal package.json for Strapi'

  # 4. Build Strapi using Nx
  - script: |
      npx nx run apps.services.editorial:build
    displayName: 'Nx build Strapi app'

  # 5. Build Docker image
  - script: |
      eval $(minikube docker-env)
      docker build -f apps/services/editorial/Dockerfile -t $(IMAGE_NAME):$(IMAGE_TAG) .
    displayName: 'Build Docker image inside Minikube'

  # 6. Deploy to Kubernetes
  - script: |
      kubectl apply -f apps/services/editorial/provisioning/k8s/editorial.deployment.yaml
      kubectl apply -f apps/services/editorial/provisioning/k8s/editorial.service.yaml
      kubectl apply -f apps/services/editorial/provisioning/k8s/editorial.service-account.yaml
    displayName: 'Deploy Strapi Deployment and Service'
