apiVersion: batch/v1
kind: CronJob
metadata:
  name: store-app-scrapper
  namespace: acquisition
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/role: "store-app-scrapper"
            vault.hashicorp.com/agent-inject-secret-queue: "secret/data/rabbitmq"
            vault.hashicorp.com/agent-inject-template-queue: |
              {{- with secret "secret/data/rabbitmq" }}
              export QUEUE_USERNAME={{ .Data.data.username }}
              export QUEUE_PASSWORD={{ .Data.data.password }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-minio: "secret/data/minio"
            vault.hashicorp.com/agent-inject-template-minio: |
              {{- with secret "secret/data/minio" -}}
              export MEDIA_STORAGE_ACCESSKEY={{ .Data.data.accesskey }}
              export MEDIA_STORAGE_SECRETKEY={{ .Data.data.secretkey }}
              {{- end }}
        spec:
          serviceAccountName: store-app
          restartPolicy: OnFailure
          containers:
            - name: scrapper
              image: store-app-scrapper:latest
              imagePullPolicy: Never
              command: ["sh", "-c"]
              args:
                - |
                  . /vault/secrets/queue && . /vault/secrets/minio && exec node dist/scrapper.js
              envFrom:
                - configMapRef:
                    name: rabbitmq-discovery