apiVersion: batch/v1
kind: Job
metadata:
  generateName: store-app-scrapper-once-
  namespace: scrapper
  labels:
    job-type: init
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "rabbitmq-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/rabbitmq"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/rabbitmq" }}
          export RABBITMQ_USER={{ .Data.data.username }}
          export RABBITMQ_PASSWORD={{ .Data.data.password }}
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      restartPolicy: OnFailure
      containers:
        - name: scrapper
          image: store-app-scrapper:latest
          imagePullPolicy: Never
          command: ["sh", "-c"]
          args:
            - |
              . /vault/secrets/config && exec node dist/scrapper.js
          envFrom:
            - configMapRef:
                name: rabbitmq-discovery
