apiVersion: batch/v1
kind: Job
metadata:
  generateName: store-app-scrapper-once-
  namespace: acquisition
  labels:
    job-type: init
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "rabbitmq-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/rabbitmq"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/rabbitmq" }}
          export QUEUE_USERNAME={{ .Data.data.username }}
          export QUEUE_PASSWORD={{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-minio: |
          {{- with secret "secret/data/minio" -}}
          export MEDIA_STORAGE_ACCESSKEY={{ .Data.data.accesskey }}
          export MEDIA_STORAGE_SECRETKEY={{ .Data.data.secretkey }}
          {{- end }}
    spec:
      serviceAccountName: store-app
      restartPolicy: OnFailure
      containers:
        - name: scrapper
          image: store-app-scrapper:latest
          imagePullPolicy: Never
          command: ["sh", "-c"]
          args:
            - |
              . /vault/secrets/config && . /vault/secrets/minio && exec node dist/scrapper.js
          envFrom:
            - configMapRef:
                name: scrapper-config
