name: 'Build and Push Docker Image'
description: 'Build and push Docker image to container registry'
inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: true
    default: './Dockerfile'
  context-path:
    description: 'Build context path'
    required: true
    default: '.'
  tags:
    description: 'Comma-separated list of tags'
    required: true
  registry:
    description: 'Container registry URL'
    required: true
    default: 'ghcr.io'
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password/token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: ${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
