trigger:
  branches:
    include:
      - master
  paths:
    include:
      - apps/agents/editor/**

variables:
  IMAGE_NAME: editor-agent
  IMAGE_TAG: latest

pool:
  name: 'Local Server Pool'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Use Node.js 18'

  - script: |
      npm install -g nx
      npm ci
    displayName: 'Install dependencies'

  - script: |
      nx build editor-agent
    displayName: 'Build editor-agent with Nx'

  - script: |
      eval $(minikube docker-env)
      docker build -f apps/agents/editor/Dockerfile -t $(IMAGE_NAME):$(IMAGE_TAG) .
    displayName: 'Build runtime-only Docker image with prebuilt dist'

  - script: |
      kubectl apply -f apps/agents/editor/provisioning/k8s/editor-agent.namespace.yaml
      kubectl apply -f apps/agents/editor/provisioning/k8s/editor-agent.service-account.yaml
      kubectl apply -f apps/agents/editor/provisioning/k8s/editor-agent.config-map.yaml
      kubectl apply -f apps/agents/editor/provisioning/k8s/editor-agent.deployment.yaml
      kubectl rollout restart deployment editor-agent -n editorial
    displayName: 'Deploy editor-agent to Kubernetes'
